package com.example.Sisegg.enums;

public enum UsoVeiculoFaculdade {
    SIM_SEM_GARAGEM,
    SIM_GARAGEM_PORTAO_MANUAL,
    SIM_GARAGEM_PORTAO_AUTOMATICO_PORTEIRO,
    SIM_GARAGEM_ESTACIONAMENTO_PRIVADO,
    NAO,
    NAO_ESTUDA;
}